import os
import sys

try:
    import pandas as pd
except ImportError:
    pd = None


class StressCompiler:
    """
    压测脚本编译器：负责把配置翻译成 Android Shell
    """

    def __init__(self, target_pkg, duration=3600, start_uri=None):
        self.target_pkg = target_pkg
        self.duration = duration
        self.start_uri = start_uri or f"{target_pkg}/.MainActivity"

    def compile(self, task_list):
        """核心编译逻辑"""
        # --- Shell 头部：监控与保活 ---
        shell = f"""#!/system/bin/sh
# Auto-generated by Dognoise Compiler
LOG_DIR="/sdcard/dognoise_stress"
mkdir -p $LOG_DIR
EVENT_LOG="$LOG_DIR/event.log"
CRASH_LOG="$LOG_DIR/crash_stack.log"

echo "=== [$(date)] 压测启动: {self.target_pkg} (时长: {self.duration}s) ===" > $EVENT_LOG

# 1. 启动日志抓取
logcat -c
nohup logcat -v time *:E -f $CRASH_LOG -r 10240 -n 5 & 
LOGCAT_PID=$!

start_time=$(date +%s)
loop_count=0

# 2. 保活函数
function ensure_app_foreground() {{
    current_focus=$(dumpsys window | grep mCurrentFocus)
    if ! echo "$current_focus" | grep -q "{self.target_pkg}"; then
        echo "[🚨 RECOVER] $(date) 应用不在前台，尝试拉起..." >> $EVENT_LOG
        am start -n {self.start_uri}
        sleep 8
    fi
}}

# 3. WiFi/蓝牙函数 (略，保持简洁，需要可自行添加)

# --- 主循环 ---
while [ $(($(date +%s) - start_time)) -lt {self.duration} ]; do

    # 死亡监控
    if [ -z "$(pidof {self.target_pkg})" ]; then
        echo "[💀 DIED] $(date) 应用进程消失" >> $EVENT_LOG
    fi

"""
        # --- 翻译任务 ---
        for task in task_list:
            action = str(task.get('action')).upper().strip()
            indent = "    "

            # 只有交互类操作才检查前台，防止点错
            if action in ["CLICK", "SWIPE", "KEY", "TEXT"]:
                shell += f"{indent}ensure_app_foreground\n"

            if action == "CLICK":
                shell += f"{indent}input tap {task.get('p1')} {task.get('p2')}\n"
            elif action == "SWIPE":
                shell += f"{indent}input swipe {task.get('p1')} {task.get('p2')} {task.get('p3')} {task.get('p4')} 300\n"
            elif action == "KEY":
                shell += f"{indent}input keyevent {task.get('p1')}\n"
            elif action == "TEXT":
                txt = str(task.get('p1')).replace(" ", "%s")
                shell += f"{indent}input text '{txt}'\n"
            elif action == "WAIT":
                shell += f"{indent}sleep {task.get('p1')}\n"
            elif action == "STOP":
                shell += f"{indent}am force-stop {self.target_pkg}\n"
            elif action == "START":
                shell += f"{indent}am start -n {self.start_uri}\n"
            elif action == "SHELL":
                shell += f"{indent}{task.get('p1')}\n"

        # --- 尾部 ---
        shell += """
    loop_count=$((loop_count + 1))
    if [ $((loop_count % 10)) -eq 0 ]; then
        echo "[Heartbeat] $(date) 运行正常 (轮次: $loop_count)" >> $EVENT_LOG
    fi
    sleep 1
done

echo "=== [$(date)] 压测结束 ===" >> $EVENT_LOG
kill $LOGCAT_PID
"""
        return shell

def run(context, **kwargs):
    """
    智能压测 V6：全指令集 + 蓝牙/WiFi + 【应用保活/防误触】
    """
    compiler = StressCompiler(
        target_pkg=kwargs.get("package_name"),
        duration=kwargs.get("duration", 3600),
        start_uri=kwargs.get("start_uri")
    )

    task_list = kwargs.get("tasks", [])
    shell_content = compiler.compile(task_list)


    try:
        local_path = os.path.join(context.root_dir, "outputs", "stress_runner_v6.sh")
        with open(local_path, "w", encoding="utf-8", newline='\\n') as f:
            f.write(shell_content)
        # ... Push & Run ...
        return {"status": True, "msg": "V6 脚本(带自愈能力)已部署"}
    except Exception as e:
        return {"status": False, "msg": str(e)}


if __name__ == "__main__":
    print("🤖 Dognoise 离线编译器启动...")

    # 1. 配置 (也可以从命令行读)
    EXCEL_FILE = "test_plan.xlsx"
    OUTPUT_DIR = "dist_stress"  # 输出目录

    # 默认配置 (防止 Excel 没填)
    DEFAULT_PKG = "com.huawei.video"
    DEFAULT_DURATION = 86400 * 3  # 3天

    if not os.path.exists(EXCEL_FILE):
        print(f"❌ 找不到 {EXCEL_FILE}，请先创建 Excel 模板！")
        sys.exit(1)

    if not pd:
        print("❌ 缺少 pandas 库，请执行: pip install pandas openpyxl")
        sys.exit(1)

    print(f"📄 正在读取: {EXCEL_FILE}")
    df = pd.read_excel(EXCEL_FILE)

    # 转换 Excel 为 Task List
    tasks = []
    # 提取第一行的配置 (如果有的话，或者硬编码)
    # 这里假设所有动作都针对同一个包

    for _, row in df.iterrows():
        act = row.get('动作类型 (Action)')
        if pd.isna(act): continue

        tasks.append({
            "action": act,
            "p1": row.get('参数1 (P1)'),
            "p2": row.get('参数2 (P2)'),
            "p3": row.get('参数3 (P3)'),
            "p4": row.get('参数4 (P4)'),
        })

    # 2. 编译
    compiler = StressCompiler(target_pkg=DEFAULT_PKG, duration=DEFAULT_DURATION)
    shell_code = compiler.compile(tasks)

    # 3. 生成交付物
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # 文件A: 核心 Shell 脚本
    sh_path = os.path.join(OUTPUT_DIR, "stress_core.sh")
    with open(sh_path, "w", encoding="utf-8", newline='\n') as f:
        f.write(shell_code)

    # 文件B: “一键启动器” (Windows BAT)
    bat_content = f"""@echo off
echo [Dognoise] 正在连接设备...
adb wait-for-device
echo [Dognoise] 设备已连接，正在注入压测脚本...

:: 推送脚本
adb push stress_core.sh /data/local/tmp/stress_core.sh
adb shell chmod 777 /data/local/tmp/stress_core.sh

:: 后台运行 (nohup)
adb shell "nohup sh /data/local/tmp/stress_core.sh > /dev/null 2>&1 &"

echo.
echo ==========================================
echo  ✅ 部署成功！脚本已在后台运行。
echo  👉 现在可以拔掉数据线了。
echo  📋 日志路径: /sdcard/dognoise_stress/
echo ==========================================
echo.
pause
"""
    bat_path = os.path.join(OUTPUT_DIR, "一键开始压测.bat")
    with open(bat_path, "w", encoding="gbk") as f:  # Windows用gbk防止乱码
        f.write(bat_content)

    print(f"\n✨ 编译完成！请将 [{OUTPUT_DIR}] 文件夹打包发给产品经理。")
    print(f"   包含: stress_core.sh + 一键开始压测.bat")